nemo_platform:
  docs_version: "26.3.1"
  chart_org: nvidian
  chart_ref: "0857255566152269/external/nemo-platform"
  chart_version: "2.0.1"
  install_doc: "https://docs.nvidia.com/nemo/microservices/26.3.1/set-up/helm/install.html"
  task_images:
    - "nvcr.io/0857255566152269/external/customizer-automodel:26.03.1"
    - "nvcr.io/0857255566152269/external/customizer-rl:26.03.1"
    - "nvcr.io/0857255566152269/external/customizer-tasks:26.03.1"
    - "nvcr.io/0857255566152269/external/nmp-cpu-tasks:26.03.1"
    - "nvcr.io/0857255566152269/external/nmp-gpu-tasks:26.03.1"

public_ngc:
  nemo_curator_image: "nvcr.io/nvidia/nemo-curator:26.04"
  nim_operator_latest_tag: "v3.1.1"
  legacy_individual_microservices_latest:
    evaluator: "25.12"
    guardrails: "25.12"
