apiVersion: v1
data:
  config.yaml: |
    platform:
      base_url: "http://nemo-core-api.nemo-peft.svc.cluster.local:8000"
      jobs_url: "http://nemo-core-api.nemo-peft.svc.cluster.local:8000"
      datastore_url: "http://nemo-data-store.nemo-peft.svc.cluster.local:3000"
      enable_service_account_auth: true
    data_designer:
      job_image: "nvcr.io/nvidia/nemo-microservices/data-designer:25.12"
      port: 8000
      assets_storage: "/artifacts_root"
      seed_dataset_source_registry:
        sources:
          - endpoint: "http://nemo-data-store.nemo-peft.svc.cluster.local:3000/v1/hf"
      model_provider_registry:
        default: "nim-120b"
        providers:
          - name: "nim-120b"
            endpoint: "http://nim-nemotron-120b.runai-rag.svc.cluster.local:8000/v1"
          - name: "kimi-k2"
            endpoint: "https://maas.apps.ocp.cloud.rhai-tmm.dev/prelude-maas/kimi-k2-6/v1"
            api_key: "KIMI_KEY"
            provider_type: "openai"
            allowed_models:
              - "kimi-k2-6"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"platform:\n  base_url: \"http://nemo-core-api.nemo-peft.svc.cluster.local:8000\"\n  jobs_url: \"http://nemo-core-api.nemo-peft.svc.cluster.local:8000\"\n  datastore_url: \"http://nemo-data-store.nemo-peft.svc.cluster.local:3000\"\n  enable_service_account_auth: true\ndata_designer:\n  job_image: \"nvcr.io/nvidia/nemo-microservices/data-designer:25.12\"\n  port: 8000\n  assets_storage: \"/artifacts_root\"\n  model_provider_registry:\n    providers:\n      - name: \"nim-120b\"\n        endpoint: \"http://nim-nemotron-120b.runai-rag.svc.cluster.local:8000/v1\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nemo-data-designer-config","namespace":"nemo-peft"}}
  creationTimestamp: "2026-05-06T15:33:21Z"
  name: nemo-data-designer-config
  namespace: nemo-peft
  resourceVersion: "36191814"
  uid: 95003ccf-2d3c-4222-8d36-9da0699a5ddd
